{{- if .Values.ruleList -}}
{{- if .Values.ruleList.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullName" . }}-rulelist
  labels:
    app: {{ include "app.name" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/resource-policy": "keep"
data:
{{- if .Values.ruleList.data }}
  rulelist.yaml: {{ print "|-" }}
    {{- with .Values.ruleList.data.whitelist }}
    whitelist:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.ruleList.data.blacklist }}
    blacklist:
      {{- toYaml . | nindent 6 }}
    {{- end }}  
{{- end }}
{{- end }}
{{- end }}