---
kind: Secret
apiVersion: v1
metadata:
  name: system-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.system_gpg }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
type: Opaque
...